### ISSUE TITLE
Remover Respostas exercícios e conteúdos protegidos

### ISSUE THREAD

**Issue by paulorla** [takeofriedrich/UDESC#1]
Oi Vinícius,

Legal o seu repositório, inclusive encorajo que você o faça. Mas tome o cuidado para remover as respostas de exercícios para que estudantes de má fé realizem plágio das respostas. Tome cuidado também para não compartilhar conteúdos que outros professores criaram (solicite permissão). Os meus você pode compartilhar sem problemas.

Abraço

**Comment by takeofriedrich** [comment]
Olá professor!

Acabei de tornar privado alguns dos arquivos que julguei necessário, os que restaram contém apenas resultados de trabalhos sem enunciados. Obrigado pelo lembrete!

Abraço.
